### ISSUE TITLE
Add Geolite2 to Add On

### ISSUE THREAD

**Issue by mrneilix** [hassio-addons/addon-tautulli#11]
## Proposed changes

Can you please add support for GeoLite2 to the add on?

**Comment by devonverdonk** [comment]
this would be very nice. any progress?

**Comment by ludeeus** [comment]
This would add 100MB to the image, I will not do that.
Bu the next version will have an option where you can DIY.
under `https://my-ha-domain.duckdns.org:8181/settings`
