### ISSUE TITLE
Tautulli start up as application

### ISSUE THREAD

**Issue by tyjtyj** [hassio-addons/addon-tautulli#149]
# Problem/Motivation
Tautulli is slowing down HA startup
> (Why the issue was filed)

## Expected behavior
Tautulli can be started as application instead of services
> (What you expected to happen)

## Actual behavior
Tautulli started before home assistant
> (What actually happened)

## Steps to reproduce
Enable auto start
> (How can someone else make/see it happen)

## Proposed changes
config,json remove startup service
https://github.com/hassio-addons/addon-tautulli/blame/99f7a1fafac7cf86bcddaa9016d1c90a7301c947/tautulli/config.json#L8

> (If you have a proposed change, workround or fix,
> describe the rationale behind it)
Tautulli is not require by home assistant on startup

**Comment by frenck** [comment]
I like that suggestion, thanks! 👍

**Comment by tyjtyj** [comment]
I wasn't sure if plex should behave the same 
home assistant may load plex sensor. 

Personally plex and tautulli can wait while home assistant should have full resources at start up. 
Well its open for discussion.

**Comment by frenck** [comment]
Well, it depends a bit. Like when these addons were made, Home Assistant was far less resilient against offline services.

Nowadays that isn't really a concern anymore.
