### ISSUE TITLE
Using admin http login requires me to erm login!

### ISSUE THREAD

**Issue by Bodge-IT** [hassio-addons/addon-tautulli#20]
# Problem/Motivation
Would love to see API token used for hassio access.
Adding the admin user and pass to tautulli means I actually have to login myself

## Expected behavior
Just jump on tautulli

## Actual behavior
Have html login screen to use and have set unmemorable user pass for html access.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
Use API for hassio addon.
It's much better.

**Comment by ludeeus** [comment]
I must disappoint you there, this will not happen.
You can however enable plex auth. 
![image](https://user-images.githubusercontent.com/15093472/52657580-491ecb00-2ef9-11e9-927f-49ea40d5eab9.png)

**Comment by Bodge-IT** [comment]
Any reason why html auth preferred over API?

**Comment by ludeeus** [comment]
Yes. it's supported by Tautulli, using that means that I do not have to change how their system works.

**Comment by Bodge-IT** [comment]
Sorry Joakim, I'm just trying to understand the issue.  Your explanation
just doesn't make sense to me.  Both features are supported by Tautulli,
only one of them is intended for app to app communitcation.

But never mind.  If it won't happen, it won't happen.
I just can't use it like this.  Thanks for contributing it though.
