### ISSUE TITLE
Multiple instances now allowed anymore

### ISSUE THREAD

**Issue by Albertjvanr** [hassio-addons/addon-tautulli#208]
# Problem/Motivation

I have more than one Plex server with Tautulli running and would like to have multiple versions of the HA integration running.

## Expected behavior

When I add a Tautulli integration while another is running it should allow me to.

## Actual behavior

The integration says I can only have one instance running. Prior to version 2022.5 of HA I was still able to configure multiple instances in yaml, but the "integration add" doesn't allow me and the yaml configuration was deprecated.

## Steps to reproduce

Try to add a Tautulli integration while an instance is already configured.

## Proposed changes

Please allow multiple integration configurations to be added. This would also mean that there would have to be an option during setup of the integration to select a desriptor ie sensor.tautulli_2 where "2" is the input during setup. I think... That's how I did it while I was still able to configure in yaml by giving the integration a "name".

**Comment by frenck** [comment]
> The integration says I can only have one instance running.

This is not the integration repository. This is that add-on repository. Add-ons and integration are not the same things. Nothing in this repository has anything to do with an integration.

../Frenck
