### ISSUE TITLE
Home Assistant supervisor logs have many schema parameter warnings related to Tautulli

### ISSUE THREAD

**Issue by jum0n** [hassio-addons/addon-tautulli#222]
# Problem/Motivation

> Home Assistant supervisor logs have many warnings related to Tautulli config params in the schema.

## Expected behavior

> No errors/warnings in supervisor logs.  

## Actual behavior

> These are the errors I am seeing:
22-07-08 21:33:43 WARNING (MainThread) [supervisor.addons.options] Option 'username' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:33:43 WARNING (MainThread) [supervisor.addons.options] Option 'password' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:33:43 WARNING (MainThread) [supervisor.addons.options] Option 'ssl' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:33:43 WARNING (MainThread) [supervisor.addons.options] Option 'certfile' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:33:43 WARNING (MainThread) [supervisor.addons.options] Option 'keyfile' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:38:47 WARNING (MainThread) [supervisor.addons.options] Option 'username' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:38:47 WARNING (MainThread) [supervisor.addons.options] Option 'password' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:38:47 WARNING (MainThread) [supervisor.addons.options] Option 'ssl' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:38:47 WARNING (MainThread) [supervisor.addons.options] Option 'certfile' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:38:47 WARNING (MainThread) [supervisor.addons.options] Option 'keyfile' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:43:51 WARNING (MainThread) [supervisor.addons.options] Option 'username' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:43:51 WARNING (MainThread) [supervisor.addons.options] Option 'password' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:43:51 WARNING (MainThread) [supervisor.addons.options] Option 'ssl' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:43:51 WARNING (MainThread) [supervisor.addons.options] Option 'certfile' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:43:51 WARNING (MainThread) [supervisor.addons.options] Option 'keyfile' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:48:55 WARNING (MainThread) [supervisor.addons.options] Option 'username' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:48:55 WARNING (MainThread) [supervisor.addons.options] Option 'password' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:48:55 WARNING (MainThread) [supervisor.addons.options] Option 'ssl' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:48:55 WARNING (MainThread) [supervisor.addons.options] Option 'certfile' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:48:55 WARNING (MainThread) [supervisor.addons.options] Option 'keyfile' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:53:59 WARNING (MainThread) [supervisor.addons.options] Option 'username' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:53:59 WARNING (MainThread) [supervisor.addons.options] Option 'password' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:53:59 WARNING (MainThread) [supervisor.addons.options] Option 'ssl' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:53:59 WARNING (MainThread) [supervisor.addons.options] Option 'certfile' does not exist in the schema for Tautulli (a0d7b954_tautulli)
22-07-08 21:53:59 WARNING (MainThread) [supervisor.addons.options] Option 'keyfile' does not exist in the schema for Tautulli (a0d7b954_tautulli)

## Steps to reproduce

> Install the add-on Tautulli and inspect the supervisor logs.

## Proposed changes

> Other add-ons have had very similar issues and its due to deprecated configuration entries, but I do not see where to remove them.
Link to very similar issue: https://community.home-assistant.io/t/errors-in-the-supervisor-logs/411527/3

**Comment by frenck** [comment]
That is not something the add-on can do anything about. You can clean up your add-on configuration (possibly via YAML mode on the add-on configuration screen).

**Comment by jum0n** [comment]
There is only one option on the config screen and its at its default.  There is no yaml for this in configuration.yaml either.

![image](https://user-images.githubusercontent.com/7494877/178111680-ad81fa8a-c4b3-4edb-9a60-d672731786cb.png)

**Comment by frenck** [comment]
![CleanShot 2022-07-09 at 17 16 48](https://user-images.githubusercontent.com/195327/178111765-0ef12a8a-1308-4277-aef1-aa4469ec0f26.png)

There is an "Edit in YAML" option in the kebab menu.

**Comment by jum0n** [comment]
Ah, yes, I found them in the YAML mode, sorry.  Thanks!!
