### ISSUE TITLE
Existing Tautulli server...

### ISSUE THREAD

**Issue by Snille** [hassio-addons/addon-tautulli#25]
# Problem/Motivation

> I would like to use my already existing installation of tautulli (on another server)

## Expected behavior

> I hoped I could just enter the IP, port, username and password for the existing server.

## Actual behavior

> A new "instans" of tautulli was installed on the Hassio (Raspberry Pi)

## Steps to reproduce

> Does not apply. 

## Proposed changes

> Make it possible to specify the IP, port, username, password (or API key)
> And then use that information instead of installing a new "instans" of tautulli.

**Comment by ludeeus** [comment]
That is how add-ons work..
It sounds like you want the platform for Home Assistant https://www.home-assistant.io/components/sensor.tautulli/

**Comment by Snille** [comment]
Thank you! I did not realize it was different things. :) I'm very new to this system.
