### ISSUE TITLE
Please support "ingress" 

### ISSUE THREAD

**Issue by Kedryn** [hassio-addons/addon-tautulli#54]
Problem/Motivation
This addon does not support "Ingress", so it's not accessible from outside LAN without opening specific ports on the router. 

Expected behavior
Support it, and it's "add to sidebar" option

**Comment by SiliconAvatar** [comment]
Unless the addon retains the non-ingress access option, this would kill the usefulness of the addon. 

The most useful feature of this addon is for creating newsletters which are accessible externally (emailed to all plex users), and without external (port based) access it would make these newsletters inaccessible to everyone else.

**Comment by Kedryn** [comment]
> Unless the addon retains the non-ingress access option, this would kill the usefulness of the addon.
> 
> The most useful feature of this addon is for creating newsletters which are accessible externally (emailed to all plex users), and without external (port based) access it would make these newsletters inaccessible to everyone else.


1) ingress has an option to work like before (non-ingress) using a port you can choose in the options
2) Ingress is for accessing the addon. It can connect to outside like before, so i can keep sending newsletter. Emails are outgoing, only

**Comment by frenck** [comment]
Some quick tests, this application doesn't play nice with Ingress, hence it will not be added.
