### ISSUE TITLE
Please update your version is so old now

### ISSUE THREAD

**Issue by Golab** [hassio-addons/addon-tautulli#63]
Can you please update the server to latest version your is V2.2.4, the admin page asks me if I wanted to upgrade version and I upgraded to V2.2.4 so I don’t know if your server was V2.2.4 but the latest from the tautulli GitHub is showing the latest version is V2.5.3

**Comment by blamaz** [comment]
Latest version is V2.5.4 now, V2.2.4 is getting old. Please consider upgrading this addon.
