### ISSUE TITLE
invalid syntax - Tautulli won't start

### ISSUE THREAD

**Issue by thundergreen** [hassio-addons/addon-tautulli#64]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
```
[16:50:29] INFO: Password is NOT in the Have I Been Pwned database! Nice!
[16:50:29] INFO: Updating running configuration...
  File "/usr/bin/crudini", line 39
    print str(e)
          ^
SyntaxError: invalid syntax
[cont-init.d] tautulli.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
```

**Comment by apedance** [comment]
I can confirm this issue.

**Comment by frenck** [comment]
This only occurs in the dev version, which is currently expected.
You should not use the dev version.
