### ISSUE TITLE
Can't use !secret in config yaml

### ISSUE THREAD

**Issue by jonastaedcke** [hassio-addons/addon-tautulli#65]
# Problem/Motivation

I just downloaded this add-on and tried to configured it.

## Expected behavior

I'd like to try !secret to insert the relevant username and password

## Actual behavior

When I type *!secret* I receive the message `Invalid YAML`. The ! isn't supported.

## Steps to reproduce

Open the configuration and insert as first line: `username: !secret plex_username`. 

## Proposed changes

I have no idea. But when this is not a possible way, the documentation has to to be changed.

Thank you :)

**Comment by frenck** [comment]
This is not an issue with the add-on, the configuration is done in Home Assistant. Please report the issue upstream.
