### ISSUE TITLE
Container failed to start (v2.0.1)

### ISSUE THREAD

**Issue by iophobia** [hassio-addons/addon-tautulli#90]
# System
Hass.io (DSM/Synology) ; supervisor-2021.02.6; core-2021.2.2 (not exactly supported, I know) 
# Problem/Motivation

Tautulli addon updated to v2.0.1, won't start anymore

## Expected behavior

Docker container starting after update

## Actual behavior

Starting via Supervisor leads to error message `400 Client Error for http+docker://localhost/v1.39/containers/fe347089e75aed7b129ba241c9d61539eaa4583a1132da5807418e55142f82cb/start: Bad Request ("OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/dev/init\": stat /dev/init: no such file or directory": unknown")`

**Comment by frenck** [comment]
DSM/Synology is not a supported system by the Home Assistant Supervised installation types. You will have more problems in the future.
